url: >
  https://0afb8f23-e02f-4bd2-a9ce-bafa1dce6d8c.app.getshifter.io:27047
name: 'It&#039;s Pronounced Metrosexual'
description: >
  Learn about gender, sexuality, and
  social justice by addressing snap
  judgments, identity, and oppression.
